Add Google Ads API redirection in issues page
googleads/google-ads-php pull request #589
Opened 2021-05-11 19:56 UTC by PierrickVoulet

Learn more information about GitHub Template Chooser configuration [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser). Here is what we set with this PR:

- Allow the creation of `blank` issues: Anyone _can_ create an issue without selecting a template
- Refer users to Google Ads API Support's page for issues that are not strictly related to the library: A new button is added to the page where the user chooses the issue template (e.g., `Question` in [Google Jax repository's template selector](https://github.com/google/jax/issues/new/choose))

2021-05-11 21:05 UTC, PierrickVoulet commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please ask general Google Ads API questions to the dedicated support
If I add "forum" then I should change for "https://groups.google.com/g/adwords-api" as well.

@fiboknacky Any preference?

2021-05-12 04:07 UTC, fiboknacky commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please ask general Google Ads API questions to the dedicated support
+1 for Laura's comment.

BTW, when will this template be used? Could you add a bit more details in the PR description?

2021-05-12 04:07 UTC, fiboknacky requested changes
Change wordings according to Laura's suggestion.

2021-05-12 12:10 UTC, PierrickVoulet commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please ask general Google Ads API questions to the dedicated support
I kept the link to Google Ads API Support's page to be future-proof and added `channels.` as suggested.

2021-05-12 13:13 UTC, fiboknacky approved these changes

2021-05-12 13:29 UTC, merged