Remove printing of GCLID in UploadConversionWithIdentifiers
googleads/google-ads-php pull request #702
Opened 2021-12-15 23:01 UTC by jradcliff

GCLID is not used in this example, so will always be absent.

2021-12-15 23:02 UTC, jradcliff commented
Credit to @AnashOommen for catching this in the Java example, which I'll fix as well.

2021-12-16 02:07 UTC, PierrickVoulet commented
Kokoro build failure will be fixed with #703.

2021-12-16 04:09 UTC, fiboknacky approved these changes

2021-12-16 04:10 UTC, fiboknacky requested changes
Could you move line 197 to line 196 too? That should fit in one line.

2021-12-16 05:03 UTC, jradcliff commented
Combined lines as requested

2021-12-16 05:13 UTC, fiboknacky reviewed
Sorry for not being clear. I meant:

```php
                printf(
                    "Uploaded conversion that occurred at '%s' to '%s'.%s",
                    $clickConversionResult->getConversionDateTime(),
                    $clickConversionResult->getConversionAction(),
                    PHP_EOL
                );
```

BTW, in this case, would the condition in the line 194 be still okay?
It's still checking `hasGclid()`.

2021-12-16 05:29 UTC, jradcliff commented
Good catch. Changed to check the conversion date time, since that's a required field. Doing the same in the updated Java example at https://github.com/googleads/google-ads-java/pull/541/files.

2021-12-16 05:30 UTC, fiboknacky approved these changes

2021-12-16 07:23 UTC, merged