Added DismissRecommendation example.
googleads/google-ads-php pull request #9
Opened 2018-12-17 11:23 UTC by fiboknacky

2018-12-18 05:54 UTC, jimper commented on examples/Recommendations/DismissRecommendation.php
> +    // Its example can be retrieved from GetTextAdRecommendations.php
```suggestion
     // An example can be retrieved from GetTextAdRecommendations.php
```

2018-12-18 05:56 UTC, jimper commented on examples/Recommendations/DismissRecommendation.php
> +    // Recommendation ID is the last alphanumeric portion of the value from
```suggestion
    // Recommendation ID is the last alphanumeric portion of the resource name obtained from
```

2018-12-18 06:01 UTC, jimper requested changes
Some minor comment suggestions, otherwise LGTM

2018-12-18 09:55 UTC, jimper commented on examples/Recommendations/DismissRecommendation.php
> +    // Recommendation ID is the last alphanumeric portion of resource name obtained from
"resource name" -> "the resource name"

2018-12-19 07:22 UTC, fiboknacky commented on examples/Recommendations/DismissRecommendation.php
> +    // Recommendation ID is the last alphanumeric portion of resource name obtained from
Done.

2018-12-19 07:25 UTC, jimper approved these changes
LGTM

2018-12-19 14:15 UTC, jradcliff approved these changes

2018-12-19 15:00 UTC, merged